"""Case Engine: groups vessel alerts into ranked investigation cases.

Usage: python -m app.case_engine

Builds one investigation case per vessel with alerts, computes a weighted
anomaly score from alert severities, generates case summaries and
recommended actions, and links source alerts as case evidence.
"""

import json
import os
from collections import defaultdict

import psycopg2
from psycopg2.extras import execute_values

DATABASE_URL = os.environ.get(
    "DATABASE_URL_SYNC",
    "postgresql://cue2case:cue2case_dev@localhost:5433/cue2case",
)

ALERT_WEIGHTS = {
    "identity_inconsistency": 0.40,
    "abnormal_approach": 0.25,
    "ais_silence": 0.20,
    "loitering": 0.15,
}

RECOMMENDATIONS = {
    "identity_inconsistency": (
        "Verify vessel identity through cross-referencing IMO registry. "
        "Check for MMSI spoofing or equipment malfunction."
    ),
    "abnormal_approach": (
        "Review vessel track replay for approach corridor compliance. "
        "Cross-reference with port authority approach instructions."
    ),
    "ais_silence": (
        "Investigate gap period. Check if vessel was in port blind spot or "
        "intentionally went dark. Request imagery for gap window."
    ),
    "loitering": (
        "Check vessel purpose and authorization for extended anchorage. "
        "Verify if vessel is awaiting berth assignment or exhibiting "
        "suspicious behavior."
    ),
}

DEFAULT_RECOMMENDATION = "Review vessel activity and alerts."
MIN_CASE_SCORE = 0.05


def priority_for_score(anomaly_score):
    """Map anomaly score to low/medium/high priority values."""
    if anomaly_score >= 0.7:
        return 3
    if anomaly_score >= 0.4:
        return 2
    return 1


def dominant_alert_type(max_severity_by_type):
    """Choose the dominant alert type using weighted contribution first."""
    return max(
        max_severity_by_type,
        key=lambda alert_type: (
            max_severity_by_type[alert_type] * ALERT_WEIGHTS.get(alert_type, 0),
            max_severity_by_type[alert_type],
            alert_type,
        ),
    )


def build_case_record(mmsi, alerts_list, vessel_info):
    """Build a case payload and evidence rows for a single vessel."""
    max_severity_by_type = {}
    alert_counts = defaultdict(int)

    for alert in alerts_list:
        alert_type = alert["alert_type"]
        alert_counts[alert_type] += 1

        current_max = max_severity_by_type.get(alert_type, 0)
        if alert["severity"] > current_max:
            max_severity_by_type[alert_type] = alert["severity"]

    anomaly_score = round(
        sum(
            max_severity_by_type.get(alert_type, 0) * weight
            for alert_type, weight in ALERT_WEIGHTS.items()
        ),
        4,
    )
    anomaly_score = min(max(anomaly_score, 0.0), 1.0)
    if anomaly_score < MIN_CASE_SCORE:
        return None

    dominant_type = dominant_alert_type(max_severity_by_type)
    vessel_name = vessel_info.get(mmsi, {}).get("name") or "Unknown Vessel"
    vessel_type = vessel_info.get(mmsi, {}).get("type")

    title = f"{vessel_name} ({mmsi}) — {dominant_type.replace('_', ' ').title()}"

    ordered_types = [
        alert_type
        for alert_type, _ in sorted(
            alert_counts.items(),
            key=lambda item: (
                -max_severity_by_type.get(item[0], 0),
                -item[1],
                item[0],
            ),
        )
    ]
    summary_parts = [
        f"{alert_counts[alert_type]} {alert_type.replace('_', ' ')} alert(s)"
        for alert_type in ordered_types
    ]
    vessel_label = f"{vessel_name} (MMSI: {mmsi})"
    if vessel_type:
        vessel_label = f"{vessel_label}, type {vessel_type}"

    summary = (
        f"Vessel {vessel_label} generated {len(alerts_list)} total alerts: "
        f"{', '.join(summary_parts)}. Composite anomaly score: "
        f"{anomaly_score:.3f}. Dominant concern: "
        f"{dominant_type.replace('_', ' ')}."
    )

    evidence_rows = [
        (
            "alert",
            alert["id"],
            json.dumps(
                {
                    "alert_type": alert["alert_type"],
                    "severity": alert["severity"],
                    "observed_at": alert["observed_at"].isoformat(),
                    "location": {"lon": alert["lon"], "lat": alert["lat"]},
                    "details": alert["details"],
                    "explanation": alert["explanation"],
                }
            ),
            f"Generated by {alert['alert_type']} detector",
        )
        for alert in alerts_list
    ]

    return {
        "mmsi": mmsi,
        "title": title,
        "anomaly_score": anomaly_score,
        "status": "new",
        "priority": priority_for_score(anomaly_score),
        "summary": summary,
        "recommended_action": RECOMMENDATIONS.get(
            dominant_type,
            DEFAULT_RECOMMENDATION,
        ),
        "evidence_rows": evidence_rows,
    }


def build_cases():
    """Build investigation cases from alerts."""
    conn = psycopg2.connect(DATABASE_URL)
    cur = conn.cursor()

    try:
        cur.execute("DELETE FROM case_evidence")
        cur.execute("DELETE FROM investigation_case")
        conn.commit()

        cur.execute(
            """
            SELECT
                id,
                mmsi,
                alert_type,
                severity,
                observed_at,
                ST_X(geom) AS lon,
                ST_Y(geom) AS lat,
                details,
                explanation
            FROM alert
            ORDER BY mmsi, observed_at, id
            """
        )
        alerts = cur.fetchall()
        print(f"Processing {len(alerts)} alerts...")

        vessel_alerts = defaultdict(list)
        for row in alerts:
            vessel_alerts[row[1]].append(
                {
                    "id": row[0],
                    "mmsi": row[1],
                    "alert_type": row[2],
                    "severity": float(row[3]),
                    "observed_at": row[4],
                    "lon": row[5],
                    "lat": row[6],
                    "details": row[7],
                    "explanation": row[8],
                }
            )

        cur.execute("SELECT mmsi, vessel_name, vessel_type FROM vessel")
        vessel_info = {
            row[0]: {"name": row[1], "type": row[2]}
            for row in cur.fetchall()
        }

        case_records = []
        for mmsi, alerts_list in vessel_alerts.items():
            case_record = build_case_record(mmsi, alerts_list, vessel_info)
            if case_record is not None:
                case_records.append(case_record)

        case_records.sort(
            key=lambda record: (-record["anomaly_score"], str(record["mmsi"]))
        )

        cases_created = 0
        evidence_created = 0
        for case_record in case_records:
            cur.execute(
                """
                INSERT INTO investigation_case (
                    title,
                    mmsi,
                    anomaly_score,
                    status,
                    priority,
                    summary,
                    recommended_action
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                RETURNING id
                """,
                (
                    case_record["title"],
                    case_record["mmsi"],
                    case_record["anomaly_score"],
                    case_record["status"],
                    case_record["priority"],
                    case_record["summary"],
                    case_record["recommended_action"],
                ),
            )
            case_id = cur.fetchone()[0]
            cases_created += 1

            if case_record["evidence_rows"]:
                execute_values(
                    cur,
                    """
                    INSERT INTO case_evidence (
                        case_id,
                        evidence_type,
                        evidence_ref,
                        data,
                        provenance
                    )
                    VALUES %s
                    """,
                    [
                        (case_id, evidence_type, evidence_ref, data, provenance)
                        for evidence_type, evidence_ref, data, provenance in case_record[
                            "evidence_rows"
                        ]
                    ],
                )
                evidence_created += len(case_record["evidence_rows"])

        conn.commit()

        cur.execute(
            """
            SELECT
                title,
                anomaly_score,
                priority,
                (
                    SELECT COUNT(*)
                    FROM case_evidence
                    WHERE case_id = investigation_case.id
                ) AS evidence_count
            FROM investigation_case
            ORDER BY anomaly_score DESC, id ASC
            LIMIT 10
            """
        )
        top_cases = cur.fetchall()

        print(f"\nCreated {cases_created} cases with {evidence_created} evidence links.")
        print("\nTop 10 cases:")
        print("-" * 80)
        for title, anomaly_score, priority, evidence_count in top_cases:
            print(
                f"  Score: {anomaly_score:.3f} | Priority: {priority} | "
                f"Evidence: {evidence_count} | {title}"
            )
    finally:
        cur.close()
        conn.close()


if __name__ == "__main__":
    build_cases()
